# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is generated by device/lenovo/manning/setup-makefiles.sh
LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),manning)

include $(CLEAR_VARS)
LOCAL_MODULE := libaudiocustparam
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := 32
LOCAL_SRC_FILES_32 := vendor/lib/libaudiocustparam.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libaudiocustparam
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := 64
LOCAL_SRC_FILES_64 := vendor/lib64/libaudiocustparam.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libmtkcam_fwkutils
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := 32
LOCAL_SRC_FILES_32 := vendor/lib/libmtkcam_fwkutils.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libmtkcam_fwkutils
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := 64
LOCAL_SRC_FILES_64 := vendor/lib64/libmtkcam_fwkutils.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libdpframework
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX = .so
LOCAL_MULTILIB := 32
LOCAL_SRC_FILES_32 := vendor/lib/libdpframework.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libdpframework
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX = .so
LOCAL_MULTILIB := 64
LOCAL_SRC_FILES_64 := vendor/lib64/libdpframework.so
include $(BUILD_PREBUILT)

# vendor pre built apks
include $(CLEAR_VARS)
LOCAL_MODULE := ConfigUpdater
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := apps/priv-app/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT)/priv-app
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := AtciService
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := apps/vendor/app/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT_VENDOR)/app
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := DrmProvider
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := apps/vendor/app/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT_VENDOR)/app
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Gba
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := apps/vendor/app/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT_VENDOR)/app
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Omacp
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := apps/vendor/app/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT_VENDOR)/app
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := YGPS
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := apps/vendor/app/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT_VENDOR)/app
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mediatek-res
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := apps/vendor/framework/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/framework
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT_VENDOR)/framework
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FwkPlugin
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := apps/vendor/plugin/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/plugin
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT_VENDOR)/plugin
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ImsService
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := apps/vendor/priv-app/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/priv-app
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT_VENDOR)/priv-app
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Stk1
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := apps/vendor/priv-app/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/priv-app
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT_VENDOR)/priv-app
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := WfoService
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := apps/vendor/priv-app/$(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/priv-app
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT_VENDOR)/priv-app
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

endif
